### ISSUE TITLE
Better avif support

### ISSUE THREAD

**Issue by rkfox** [image-rs/image#1504]
I would like to be able to decode 10-bit avif images. It appears that cavif-rs outputs 10-bit avif images that cannot be decoded using image-rs.

**Comment by rkfox** [comment]
I looked through cavif-rs and it appears to only output 8-bit avif files so I'm not sure what is going on here since image-rs lists decode support for 8-bit avif files. The image loads fine in Chromium, but image-rs cannot decode it.

The image was encoded like this:
`cavif --speed 1 --quality 60 SampleJPGImage_500kbmb.jpg`
![SampleJPGImage_500kbmb](https://user-images.githubusercontent.com/73992121/124391532-04a94b00-dcbf-11eb-900b-c0fea6cffba9.jpg)

Github does not support attaching .avif files.

**Comment by fintelia** [comment]
Are you able to upload a zipped version of the file?

**Comment by baumanj** [comment]
@rkfox: you can check the file with https://gpac.github.io/ComplianceWarden-wasm/avif.html to see if it was invalidly encoded

**Comment by rkfox** [comment]
It did not pass validation.

> Result:
> Compliance Warden, version v28-master-rev0-g29d5bb7.
> +--------------------------------------+
> | avif validation |
> +--------------------------------------+
> 
> Specification description: AVIF v1.0.0, 19 February 2019
> https://aomediacodec.github.io/av1-avif/
> 
> [avif][Rule #7] Error: The values of the AV1CodecConfigurationBox shall match
> the Sequence Header OBU in the AV1 Image Item Data:
> AV1CodecConfigurationBox:
> seq_profile=0
> seq_level_idx_0=0
> seq_tier_0=0
> high_bitdepth=0
> twelve_bit=0
> mono_chrome=0
> chroma_subsampling_x=0
> chroma_subsampling_y=0
> chroma_sample_position=0
> Sequence Header OBU in the AV1 Image Item Data:
> seq_profile=1
> seq_level_idx_0=31
> seq_tier_0=0
> high_bitdepth=0
> twelve_bit=0
> mono_chrome=0
> chroma_subsampling_x=0
> chroma_subsampling_y=0
> chroma_sample_position=0
> 
> [avif][Rule #9] Error: Transformative property "av1C" shall be marked as essential (item_ID=1)
> 
> ========================================
> [avif] 2 error(s), 0 warning(s).
> ========================================
> 
> ===== Involved rules descriptions:
> 
> [avif][Rule #7] Section 2.2.1
> The values of the fields in the AV1CodecConfigurationBox shall match those of the
> Sequence Header OBU in the AV1 Image Item Data.
> 
> [avif][Rule #9] Section 2.2.1
> AV1 Item Configuration Property [...] shall be marked as essential.
> 
> +--------------------------------------+
> | miaf validation |
> +--------------------------------------+
> 
> Specification description: MIAF (Multi-Image Application Format)
> MPEG-A part 22 - ISO/IEC 23000-22 - w18260 FDIS - Jan 2019
> 
> [miaf][Rule #2] Error: compatible_brands list shall contain 'miaf' (not found) and 'mif1' (found)
> 
> ========================================
> [miaf] 1 error(s), 0 warning(s).
> ========================================
> 
> ===== Involved rules descriptions:
> 
> [miaf][Rule #2] Section 7.2.1.2
> The FileTypeBox shall contain, in the compatible_brands list,
> the following (in any order): 'mif1' (specified in ISO/IEC 23008-12)
> [...]
> Files conforming to the general restrictions in clause 7 shall include
> the brand 'miaf' in the compatible_brands in the FileTypeBox.
> 
> +--------------------------------------+
> | heif validation |
> +--------------------------------------+
> 
> Specification description: HEIF - ISO/IEC 23008-12 - 2nd Edition N18310
> 
> ========================================
> [heif] No errors.
> ========================================
> 
> +--------------------------------------+
> | isobmff validation |
> +--------------------------------------+
> 
> Specification description: ISO Base Media File Format
> MPEG-4 part 12 - ISO/IEC 14496-12 - m17277 (6th+FDAM1+FDAM2+COR1-R4)
> 
> ========================================
> [isobmff] No errors.
> ========================================
>

**Comment by baumanj** [comment]
[Here's an AVIF version](https://github.com/image-rs/image/files/6803362/SampleJPGImage_500kbmb.libavif.avif.zip) of your JPEG encoded with libavif which _does_ pass validation. I believe there are some compliance issues with [cavif-rs](https://github.com/kornelski/cavif-rs) (or more precisely [avif-serialize](https://github.com/kornelski/avif-serialize)).

The reason the cavif-rs-encoded file appears fine in the browser (at least in Firefox; chromium uses a different library for parsing) is that it's using a newer version of mp4parse that hasn't been published on crates.io. There's been [significant updates to the compliance-related functionality](https://github.com/mozilla/mp4parse-rust/issues?q=label%3Acompliance+label%3Aavif+) since the last time I published to crates.io. If the newer version would be helpful (this can be tested by changing [the dependency on `mp4parse` in Cargo.toml](https://github.com/image-rs/image/blob/18c90d03ca436822270725daeceab8033ac076bc/Cargo.toml#L36) to `mp4parse = { git = "https://github.com/mozilla/mp4parse-rust" }`), then I'd be happy to set aside some time to publish a newer version.

**Comment by rkfox** [comment]
I am still unable to open AVIF images with image-rs that pass ComplianceWarden validation without any errors.

**Comment by mockfox** [comment]
Just an update on this. `image` cannot decode images encoded by libavif 0.9.0 with libaom.
`thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Decoding(DecodingError { format: Exact(Avif), underlying: Some(InvalidOperation) })', src/main.rs:2:31`
[image.zip](https://github.com/image-rs/image/files/8693645/image.zip)
